name: MyApp
author: Jérome Eertmans
description: My super Rust application
branding:  # You can change this
  icon: align-left
  color: blue
inputs:
  args:
    description: Arguments passed to `myapp`
    required: true
    default: ''
outputs:
  results:
    description: The results from calling `myapp`
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.args }}
